--- #YAML:1.0
name:               ProgressBar-Stack
version:            1.01
abstract:           Progress bar implementation with stack support and useful loop wrappers
author:
    - Tagir Valeev <lan@nprog.ru>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::Util:   0
    Test::More:   0
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
